apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spef-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: spef
  namespace: default
roleRef:
  kind: Role
  name: spef-role
  apiGroup: rbac.authorization.k8s.io

