apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: spef-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services", "configmaps", "secrets"] # Add any other necessary resources
  verbs: ["get", "list", "watch", "create", "update", "delete"] # Adjust as needed

