---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: subbhashit
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "23subbhashit/spemajorf"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -d --name minispe 23subbhashit/spemajorf
