- name: Deploy Docker image and Kubernetes resources for spemajorf
  hosts: localhost
  remote_user: subbhashit
  become: false
  tasks:
    - name: Apply Kubernetes Deployment files
      k8s:
        state: present
        src: "{{ item }}"
        namespace: your-namespace
      with_fileglob:
        - ../kubernetes/*.yaml
