apiVersion: apps/v1
kind: Deployment
metadata:
  name: spemajorf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spemajorf
  template:
    metadata:
      labels:
        app: spemajorf
    spec:
      serviceAccountName: fork8s  # Use the fork8s ServiceAccount
      containers:
        - name: spemajorf-container
          image: 23subbhashit/spemajorf
          ports:
            - containerPort: 3000
